---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 79397.
--- DateTime: 2022/12/27 20:33
---
local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]

local stockKey = 'seckill:stock'..voucherId
local orderKey = 'seckill:order'..voucherId

if (tonumber(redis.call('get', stockKey)) <= 0) then
    -- not enough stock
    return 1
end
if (redis.call('sismember', orderKey, userId) == 1) then
    return 2
end
-- decrease stock and save user info
redis.call('incrby', stockKey, -1)
redis.call('sadd', orderKey, userId)
-- send msg to queue
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)

return 0
